import os
import json
import argparse

import numpy as np
import matplotlib.pyplot as plt

from sklearn.preprocessing import label_binarize

from sklearn.metrics import (
    roc_curve,
    auc,
    precision_recall_curve,
    average_precision_score
)
def main():

    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--result_dir",
        required=True,
        help="Folder generated by test.py"
    )

    args = parser.parse_args()
    probabilities = np.load(
        os.path.join(
            args.result_dir,
            "probabilities.npy"
        )
    )

    labels = np.load(
        os.path.join(
            args.result_dir,
            "labels.npy"
        )
    )

    analysis_dir = os.path.join(
        args.result_dir,
        "analysis"
    )

    os.makedirs(
        analysis_dir,
        exist_ok=True
    )
    print("\nROC / PR Analysis")
    print("-" * 40)
    print("Labels :", labels.shape)
    print("Probabilities :", probabilities.shape)
    print("-" * 40)
    n_classes = probabilities.shape[1]

    labels_bin = label_binarize(
        labels,
        classes=np.arange(n_classes)
    )
    fpr = {}
    tpr = {}
    roc_auc = {}

    for i in range(n_classes):

        fpr[i], tpr[i], _ = roc_curve(
            labels_bin[:, i],
            probabilities[:, i]
        )

        roc_auc[i] = auc(
            fpr[i],
            tpr[i]
        )
        plt.figure(figsize=(8,6))

    for i in range(n_classes):

        plt.plot(
            fpr[i],
            tpr[i],
            label=f"Class {i} (AUC={roc_auc[i]:.3f})"
        )

    plt.plot(
        [0,1],
        [0,1],
        linestyle="--",
        color="gray"
    )

    plt.xlabel("False Positive Rate")

    plt.ylabel("True Positive Rate")

    plt.title("ROC Curve")

    plt.legend()

    plt.grid(alpha=0.3)

    plt.tight_layout()

    plt.savefig(
        os.path.join(
            analysis_dir,
            "roc_curve.png"
        ),
        dpi=300
    )

    plt.savefig(
        os.path.join(
            analysis_dir,
            "roc_curve.pdf"
        ),
        bbox_inches="tight"
    )

    plt.close()

    precision = {}
    recall = {}
    ap = {}

    for i in range(n_classes):

        precision[i], recall[i], _ = precision_recall_curve(
            labels_bin[:, i],
            probabilities[:, i]
        )

        ap[i] = average_precision_score(
            labels_bin[:, i],
            probabilities[:, i]
        )
        plt.figure(figsize=(8,6))

    for i in range(n_classes):

        plt.plot(
            recall[i],
            precision[i],
            label=f"Class {i} (AP={ap[i]:.3f})"
        )

    plt.xlabel("Recall")

    plt.ylabel("Precision")

    plt.title("Precision-Recall Curve")

    plt.legend()

    plt.grid(alpha=0.3)

    plt.tight_layout()

    plt.savefig(
        os.path.join(
            analysis_dir,
            "pr_curve.png"
        ),
        dpi=300
    )

    plt.savefig(
        os.path.join(
            analysis_dir,
            "pr_curve.pdf"
        ),
        bbox_inches="tight"
    )

    plt.close()

    roc_pr_stats = {

        "roc_auc": {
            str(i): float(roc_auc[i])
            for i in range(n_classes)
        },

        "average_precision": {
            str(i): float(ap[i])
            for i in range(n_classes)
        },

        "macro_auc": float(np.mean(list(roc_auc.values()))),

        "macro_ap": float(np.mean(list(ap.values())))
    }

    with open(
        os.path.join(
            analysis_dir,
            "roc_pr_statistics.json"
        ),
        "w"
    ) as f:

        json.dump(
            roc_pr_stats,
            f,
            indent=4
        )
    
    print("\nROC / PR Analysis Completed")

    print(f"Results saved to: {analysis_dir}")


if __name__ == "__main__":
    main()