import os
import json

import numpy as np
import matplotlib.pyplot as plt
import argparse
from scipy.stats import mannwhitneyu

def get_statistics(values):

    return {

        "mean": float(np.mean(values)),
        "std": float(np.std(values)),
        "min": float(np.min(values)),
        "max": float(np.max(values)),
        "median": float(np.median(values)),
        "q1": float(np.percentile(values,25)),
        "q3": float(np.percentile(values,75))
    }

def print_statistics(name, values):

    print(f"\n{name}")
    print("-"*40)

    print(f"Mean   : {values.mean():.4f}")
    print(f"Std    : {values.std():.4f}")
    print(f"Min    : {values.min():.4f}")
    print(f"Max    : {values.max():.4f}")

    print("-"*40)

def save_histogram(values, title, filename, analysis_dir):
    plt.figure(figsize=(7,5))
    plt.hist(
        values,
        bins=40,
        edgecolor="black"
    )
    plt.title(title)
    plt.xlabel(title)
    plt.ylabel("Samples")
    plt.grid(alpha=0.3)
    plt.tight_layout()
    # PNG
    plt.savefig(
        os.path.join(
            analysis_dir,
            filename
        ),
        dpi=300
    )

    # PDF
    plt.savefig(
        os.path.join(
            analysis_dir,
            filename.replace(".png", ".pdf")
        ),
        bbox_inches="tight"
    )
    plt.close()
    
def main():

    parser = argparse.ArgumentParser()

    parser.add_argument(
        "--result_dir",
        required=True,
        help="Folder generated by test.py"
    )

    args = parser.parse_args()
    trust = np.load(
        os.path.join(args.result_dir, "trust.npy")
    )
    confidence = np.load(
        os.path.join(args.result_dir, "confidence.npy")
    )
    entropy = np.load(
        os.path.join(args.result_dir, "entropy.npy")
    )
    anomaly = np.load(
        os.path.join(args.result_dir, "anomaly.npy")
    )
    temperature = np.load(
        os.path.join(args.result_dir, "temperature.npy")
    )
    disagreement = np.load(
        os.path.join(args.result_dir, "disagreement.npy")
    )
    labels = np.load(
        os.path.join(args.result_dir, "labels.npy")
    )
    predictions = np.load(
        os.path.join(args.result_dir, "predictions.npy")
    )
    features = np.load(
        os.path.join(args.result_dir, "features.npy")
    )

    print("\nLoaded Analysis Data")
    print("-"*40)
    print("Trust:", trust.shape)
    print("Confidence:", confidence.shape)
    print("Entropy:", entropy.shape)
    print("Temperature:", temperature.shape)
    print("Anomaly:", anomaly.shape)
    print("Disagreement:", disagreement.shape)
    print("Labels:", labels.shape)
    print("Predictions:", predictions.shape)
    print("Features:", features.shape)
    print("-"*40)

    assert len(trust) == len(labels)
    assert len(confidence) == len(labels)
    assert len(entropy) == len(labels)
    assert len(anomaly) == len(labels)
    assert len(disagreement) == len(labels)
    assert len(temperature) == len(labels)

    analysis_dir = os.path.join(
        args.result_dir,
        "analysis"
    )

    os.makedirs(
        analysis_dir,
        exist_ok=True
    )

    trust_stats = get_statistics(trust)

    print("\nTrust Statistics")
    print("-"*40)

    for k, v in trust_stats.items():
        print(f"{k:10s}: {v:.4f}")

    print("-"*40)

    with open(
        os.path.join(
            analysis_dir,
            "trust_statistics.json"
        ),
        "w"
    ) as f:

        json.dump(
            trust_stats,
            f,
            indent=4
        )

    

    plt.figure(figsize=(8,5))

    plt.hist(
        trust,
        bins=50,
        edgecolor="black"
    )

    plt.xlabel("Trust Score")
    plt.ylabel("Samples")
    plt.title("Trust Score Distribution")
    plt.grid(alpha=0.3)
    plt.tight_layout()
    plt.savefig(
        os.path.join(
            analysis_dir,
            filename
        ),
        dpi=300
    )

    plt.close()
    plt.figure(figsize=(7,2))
    plt.boxplot(
        trust,
        vert=False
    )

    plt.xlabel("Trust Score")
    plt.title("Trust Score Boxplot")
    plt.tight_layout()
    plt.savefig(
        os.path.join(
            analysis_dir,
            pdf_name
        ),
        dpi=300
    )

    plt.close()
    correct_mask = (labels == predictions)
    incorrect_mask = ~correct_mask
    trust_correct = trust[correct_mask]
    trust_incorrect = trust[incorrect_mask]
    print("\nTrust vs Correctness")
    print("-"*40)
    print(f"Correct Samples   : {len(trust_correct)}")
    print(f"Incorrect Samples : {len(trust_incorrect)}")
    print(f"Mean Trust (Correct)   : {trust_correct.mean():.4f}")
    print(f"Mean Trust (Incorrect) : {trust_incorrect.mean():.4f}")
    print("-"*40)

    plt.figure(figsize=(6,5))
    plt.boxplot(
        [trust_correct, trust_incorrect],
        labels=["Correct", "Incorrect"]
    )
    plt.ylabel("Trust Score")
    plt.title("Trust Score vs Prediction Correctness")
    plt.grid(alpha=0.3)
    plt.tight_layout()
    plt.savefig(
        os.path.join(
            analysis_dir,
            "trust_vs_correct.png"
        ),
        dpi=300
    )

    plt.close()
    plt.figure(figsize=(8,5))
    plt.hist(
    trust_correct,
        bins=40,
        alpha=0.6,
        label="Correct"
    )

    plt.hist(
        trust_incorrect,
        bins=40,
        alpha=0.6,
        label="Incorrect"
    )

    plt.xlabel("Trust Score")
    plt.ylabel("Samples")
    plt.title("Trust Distribution by Prediction Correctness")
    plt.legend()
    plt.grid(alpha=0.3)
    plt.tight_layout()
    plt.savefig(
        os.path.join(
            analysis_dir,
            "trust_correct_histogram.png"
        ),
        dpi=300
    )

    plt.close()
    stat, p = mannwhitneyu(
        trust_correct,
        trust_incorrect,
        alternative="greater"
    )

    print(f"Mann-Whitney U p-value: {p:.6e}")

    analysis_stats = {
        "trust": get_statistics(trust),
        "confidence": get_statistics(confidence),
        "entropy": get_statistics(entropy),
        "anomaly": get_statistics(anomaly),
        "disagreement": get_statistics(disagreement),
        "temperature": get_statistics(temperature)
    }

    analysis_stats["mann_whitney"] = {
        "statistic": float(stat),
        "p_value": float(p)
    }

    with open(
        os.path.join(
            analysis_dir,
            "analysis_statistics.json"
        ),
        "w"
    ) as f:

        json.dump(
            analysis_stats,
            f,
            indent=4
        )
    
    print_statistics("Trust", trust)

    #print_statistics("Confidence", confidence)
    #print_statistics("Entropy", entropy)
    #print_statistics("Anomaly", anomaly)
    #print_statistics("Disagreement", disagreement)
    #print_statistics("Temperature", temperature)

    print("\nAnalysis completed successfully.")
    print(f"Results saved to: {analysis_dir}")

    plots = {

        "confidence_distribution.png":
            ("Teacher Confidence", confidence),

        "entropy_distribution.png":
            ("Teacher Entropy", entropy),

        "anomaly_distribution.png":
            ("Anomaly Score", anomaly),

        "disagreement_distribution.png":
            ("Teacher Disagreement", disagreement),

        "temperature_distribution.png":
            ("Adaptive Temperature", temperature)
    }
    for filename, (title, values) in plots.items():
        save_histogram(values, title, filename, analysis_dir)

if __name__ == "__main__":
    main()